import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const root='/home/alexandre/GPT_slot8';
const code=fs.readFileSync(path.join(root,'src/data/quiz-data.js'),'utf8');
const sandbox={window:{}}; vm.createContext(sandbox); vm.runInContext(code,sandbox);
const d=sandbox.window.QUIZ_DATA;
const cand=Object.fromEntries(d.candidates.map(c=>[c.slug,c]));
const out=path.join(root,'docs/analysis'); fs.mkdirSync(path.join(out,'candidates'),{recursive:true});
const cross=['# Matriz de evidências das 10 perguntas','','Esta matriz é derivada dos PDFs oficiais do TSE preservados em `data/raw-pdfs/` e indexados página a página em `data/pages/`. As descrições são paráfrases curtas; a referência de página aponta para o PDF oficial.','','**Regra conservadora:** uma candidatura só aparece associada a uma alternativa quando o plano sustenta claramente aquela direção. Ausência de associação não significa posição contrária.',''];
d.questions.forEach((q,i)=>{ cross.push('## '+(i+1)+'. '+q.theme+' — '+q.prompt,'',q.context,''); q.options.forEach(o=>{ cross.push('### '+o.label,'',o.detail,''); o.matches.slice().sort((a,b)=>cand[a.candidate].name.localeCompare(cand[b.candidate].name,'pt-BR')).forEach(x=>{const c=cand[x.candidate], ps=x.pages.map(p=>'p.'+p).join(', '); cross.push('- **'+c.name+' ('+c.party+')** — '+x.evidence+' ('+ps+')');}); cross.push(''); }); });
fs.writeFileSync(path.join(out,'crosswalk.md'),cross.join('\n')+'\n');
fs.writeFileSync(path.join(out,'quiz-design.md'),['# Desenho do quiz','','## Objetivo','','Apresentar escolhas de política pública sem revelar candidaturas durante as respostas e, ao final, mostrar correspondências documentais por tema.','','## O resultado não faz','','- não soma pontos por candidatura;','- não calcula porcentagem global de afinidade;','- não escolhe um “mais compatível”;','- não recomenda voto;','- não infere posição por partido, histórico, entrevista ou rede social.','','## O resultado faz','','Para cada uma das 10 perguntas, mostra a alternativa escolhida e os planos oficiais que contêm uma direção materialmente compatível, com página, paráfrase e link para o documento integral no TSE.','','## Proteções contra falso alinhamento','','1. Ausência no plano não é convertida em oposição.','2. Alternativas com mecanismos diferentes permanecem separadas, ainda que compartilhem um objetivo geral.','3. Propostas singulares têm alternativas próprias quando necessário.','4. “Prefiro não responder” existe em todas as perguntas.','5. As alternativas são embaralhadas a cada início de teste; a opção de não resposta permanece por último.','6. Candidaturas só são reveladas depois do fim do quiz.','7. Na revelação, a ordem é alfabética e independe das respostas.','8. Nenhum dado pessoal é necessário para fazer o teste.',''].join('\n'));
fs.writeFileSync(path.join(out,'reading-log.md'),['# Registro de leitura e análise','','## Corpus','','- 13 planos oficiais disponibilizados pelo TSE;','- 836 páginas no total;','- 33.655 linhas de texto extraídas;','- PDFs originais preservados com SHA-256;','- todas as páginas separadas e indexadas em JSON.','','## Processo','','1. Download dos PDFs diretamente dos endereços oficiais do TSE.','2. Validação dos arquivos e geração de hashes.','3. Extração integral preservando o layout.','4. Separação e indexação página a página.','5. Varredura temática do corpus completo para localizar trechos relevantes.','6. Leitura dirigida das páginas de maior relevância e de páginas adjacentes, distinguindo objetivo, instrumento e grau de compromisso.','7. Construção conservadora das alternativas: só associações explicitamente sustentadas pelo plano entram no quiz.','8. Revisão cruzada de propostas semelhantes para não fundir mecanismos diferentes.','9. Geração automática da documentação a partir do mesmo dataset consumido pelo site.','','## Auditoria','','O corpus integral permanece no repositório. A interface pública usa paráfrases curtas, referências de página e links aos documentos oficiais completos.',''].join('\n'));
for(const c of d.candidates){ const rows=[]; for(const q of d.questions) for(const o of q.options) for(const x of o.matches) if(x.candidate===c.slug) rows.push({theme:q.theme,label:o.label,evidence:x.evidence,pages:x.pages}); const lines=['# '+c.name+' — '+c.party,'','- Número: **'+c.number+'**','- Plano oficial: '+c.planUrl,'- Extensão: **'+c.pages+' páginas**','','## Posições utilizadas nas 10 perguntas','', '> Este dossiê registra as posições efetivamente utilizadas no comparador. Não pretende resumir todo o programa.','']; if(rows.length){lines.push('| Tema | Direção documentada | Evidência resumida | Página(s) |','|---|---|---|---|'); rows.forEach(r=>lines.push('| '+r.theme+' | '+r.label+' | '+r.evidence.replaceAll('|','\\|')+' | '+r.pages.map(p=>'p.'+p).join(', ')+' |'));} else lines.push('Nenhuma posição deste plano foi usada na versão atual das dez perguntas.'); lines.push('','## Arquivos de auditoria','','- Texto integral: `data/text/'+c.slug+'.txt`','- Índice página a página: `data/pages/'+c.slug+'.json`','- PDF preservado: `data/raw-pdfs/'+c.slug+'.pdf`',''); fs.writeFileSync(path.join(out,'candidates',c.slug+'.md'),lines.join('\n')); }
console.log('docs generated:',d.questions.length,'questions,',d.candidates.length,'candidates');